### ISSUE TITLE
Capability wrong name selection

### ISSUE THREAD

**Issue by evinxnl** [skogsaas/homey.dashboards#120]
everything is set to (aanzetten)
no device names ?

how to fix this ?

![image](https://github.com/skogsaas/homey.dashboards/assets/81700899/4b8204ad-d026-4026-8f1a-313a02b9c971)

**Comment by skogsaas** [comment]
Hi
You have to override the title of each capability yourself. The name of the capability itself is just "Aangezet", the device name is not included as a part of the capability name when displaying the components, only when using the CapabilityPicker to search and select.

If I change this default behaviour, 100+ people are going to complain about me ruining their dashboards 😅

**Comment by evinxnl** [comment]
sorry my bad i found it after i reboot the homey pro this field was editable
