### ISSUE TITLE
i have 2 different dashboards ?

### ISSUE THREAD

**Issue by evinxnl** [skogsaas/homey.dashboards#121]
I made a dashboard on my desktop

but if i login by phone there is no dashboard and i need to create a new one

what am i doing wrong ?

i try 
local (direct)
local (online)
remote url
github

but every dashboard get its own ID 

how do i make 1 dashboard that i can use on multiply devices ?

**Comment by skogsaas** [comment]
In your native Homey App, add a device of type Dashboard. Whatever you name that device, it will show up as a dashboard using any of the login methods you have listed ;)

**Comment by evinxnl** [comment]
ah thank you i thought that was a real device you want to connect (a screen or something)
