### ISSUE TITLE
buttons are to close at each other how to fix that ?

### ISSUE THREAD

**Issue by evinxnl** [skogsaas/homey.dashboards#122]
maybe im doing something wrong but some buttons are very close to each other not a very nice look (if you ask me)

what can i do ?

![image](https://github.com/skogsaas/homey.dashboards/assets/81700899/e55eac71-900a-405f-ad61-66174de25925)

https://github.com/skogsaas/homey.dashboards/assets/81700899/515c38c5-6c38-46c3-b0e6-ece55683137a

**Comment by skogsaas** [comment]
Nothing you can do right now. Planned changes will allow you to apply margin and padding.

**Comment by evinxnl** [comment]
great news 😃 thanks for all your effort and quick responds
