### ISSUE TITLE
Dashboard not transferable between devices

### ISSUE THREAD

**Issue by alexanitavanrossum** [skogsaas/homey.dashboards#14]
I have build the dashboard on my pc. 
But when i wan't to view it on another device, the screen stays blank. only thing i see is the toolbar.

**Comment by skogsaas** [comment]
I recommend not trying to build the app manually, but instead install the app from Homey App Store. Read the first post on the community forum: https://community.homey.app/t/app-pro-dashboards-custom-dashboards-for-your-homey/84837#getting-started-1. If you have a HP23, you can access the prebuilt app from the Homey itself by navigating to the Dashboards app configuration page. If you have a HP16/HP19, you have to use the online version at https://homeyboard.github.io.
