### ISSUE TITLE
WIDGET: Add iframe widget with sandboxing

### ISSUE THREAD

**Issue by skogsaas** [skogsaas/homey.dashboards#53]

**Comment by baloe1541** [comment]
Would be nice feature

**Comment by baloe1541** [comment]
Hope it’s possible

**Comment by skogsaas** [comment]
Comment from duplicate #97 :

- disclaimer on cross-site scripting warning/code injection, ie only embed iframes from trusted sites
- add mandatory height & width property. otherwise the scaling of the iframe could be funny. it would show then with fixed size in the dashboard. but otherwise it might be challenging to dynamically size it without having insight of the content

**Comment by skogsaas** [comment]
Implemented in 0.14.0
