### ISSUE TITLE
UI: support for iframe

### ISSUE THREAD

**Issue by draoZA** [skogsaas/homey.dashboards#97]
Hi, it would be great to **support for iframes**. When you embed infos from other websites they often only offer iframe integration. Examples: weather summary, google maps,...

iframes have some inherit disadvantages though. So I would add:
- **disclaimer** on cross-site scripting warning/code injection, ie only embed iframes from trusted sites
- add m**andatory height & width property**. otherwise the scaling of the iframe could be funny. it would show then with fixed size in the dashboard. but otherwise it might be challenging to dynamically size it without having insight of the content

**Comment by skogsaas** [comment]
Duplicate of #53 . I'll copy the comment to that issue instead.
